### ISSUE TITLE
Release: apt-buildpack (Apr)

### ISSUE THREAD

**Issue by cf-buildpacks-eng** [cloudfoundry/apt-buildpack#131]
Release reminder for apt-buildpack

* See [diff from latest version](https://github.com/cloudfoundry/apt-buildpack/compare/v0.3.0..develop) and validate if a release is required.
* Make sure the latest commit on  has passed tests on the [CI](https://buildpacks.ci.cf-app.com/teams/main/pipelines/apt-buildpack)
* Refer [release instructions](https://github.com/pivotal-cf/tanzu-buildpacks/wiki/Releasing-CF-Buildpacks). (private link)

**Comment by arjun024** [comment]
PR to fix tests https://github.com/cloudfoundry/apt-buildpack/pull/133

**Comment by arjun024** [comment]
There's only test code changes and no buildpack changes. Hence a release in not required
