### ISSUE TITLE
Unable to deploy NodeJS app with cflinuxfs4

### ISSUE THREAD

**Issue by shubham-gupta-nerdware** [cloudfoundry/apt-buildpack#135]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
CLI version 8.4.0+b4c083e.2022-06-02

What version of the buildpack you are using?
Latest

If you were attempting to accomplish a task, what was it you were attempting to do?
I am trying to deploy a multi-buildpack NodeJs application on BTP which needs some linux libraries[attached in this issues], it is working fine with `cflinuxfs3` but throwing error with `cflinuxfs4`

```code 
ERR Failed to compress droplet filesystem: exit status 2
ERR Failed to stage build: staging failed
```

-- My multi-buildpack.yml
```yml
buildpacks:
  - https://github.com/cloudfoundry/apt-buildpack#v0.3.0
  - https://github.com/cloudfoundry/nodejs-buildpack/
```
[apt.yml.txt](https://github.com/cloudfoundry/apt-buildpack/files/11199764/apt.yml.txt)
[cf.log](https://github.com/cloudfoundry/apt-buildpack/files/11199786/cf.log)

What did you expect to happen?
The application is deployed successfully

What was the actual behavior?
Getting error  when running `cf push -s cflinuxfs4 -f ./manifest.yml`
```code 
ERR Failed to compress droplet filesystem: exit status 2
ERR Failed to stage build: staging failed
```

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by shubham-gupta-nerdware** [comment]
Hi @arjun024, can you please help here, its little urgent.
Thanks!

**Comment by shubham-gupta-nerdware** [comment]
I am able to fix this, it was because of `xdg-utils`, it seems `Ubuntu 22.04` is unable to install this.
As i do not need this package, I a, closing this issue now.

**Comment by arjun024** [comment]
@shubham-gupta-nerdware  Thanks for your report.
Well, from the logs it looks those `ERR Failed to compress droplet filesystem: exit status 2` comes from the nodejs buildpack and not the apt buildpack. I'm curious to understand why that happened. Would you willing to share a sample app?
