### ISSUE TITLE
Failing for cflinuxfs3 - Unable to initialize apt package: open /etc/apt/trusted.gpg

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/apt-buildpack#15]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

* PWS with cflinuxfs3 stack.

What version of the buildpack you are using?

* git/master/HEAD

If you were attempting to accomplish a task, what was it you were attempting to do?

I wanted the glorious benefits of cflinuxfs3/ubuntu 18.08 with apt-buildpack - newer packages + hopefully newer imagemagick in the stack.

What did you expect to happen?

Ruby + Apt buildpacks to do their thing.

What was the actual behavior?

```
Staging app and tracing logs...
   Downloaded ruby_buildpack (263.8M)
   Cell 26c41a05-0278-476c-a153-75f61619a1cd creating container for instance 22458e2a-7b1b-4afa-89e3-0611c6b06d96
   Cell 26c41a05-0278-476c-a153-75f61619a1cd successfully created container for instance 22458e2a-7b1b-4afa-89e3-0611c6b06d96
   Downloading app package...
   Downloaded app package (9.8M)
   -----> Download go 1.9.1
   -----> Running go build supply
   .
   ./final
   ./1986c11e5045899f72e33ebceb13b732
   -----> Apt Buildpack version 0.1.2
          **ERROR** Unable to initialize apt package: open /etc/apt/trusted.gpg: no such file or directory
   Failed to run all supply scripts: exit status 13
```

**Comment by drnic** [comment]
I also tried `https://github.com/cloudfoundry/apt-buildpack#develop` since master branch dates back to April 2018.

**Comment by sclevine** [comment]
Closing: this was shipped a while ago
