### ISSUE TITLE
Cannot install packages on cflinuxfs3

### ISSUE THREAD

**Issue by norman-abramovitz** [cloudfoundry/apt-buildpack#17]
It looks like apt update cannot be run on cflinuxfs3

What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

Normans-MacBook-Pro:ghost-for-cloudfoundry Norman$ cf curl /v2/info; cf version
{
   "name": "",
   "build": "",
   "support": "https://support.run.pivotal.io",
   "version": 0,
   "description": "Cloud Foundry sponsored by Pivotal",
   "authorization_endpoint": "https://login.run.pivotal.io",
   "token_endpoint": "https://uaa.run.pivotal.io",
   "min_cli_version": "6.22.0",
   "min_recommended_cli_version": "latest",
   "app_ssh_endpoint": "ssh.run.pivotal.io:2222",
   ...
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.run.pivotal.io:443",
   "api_version": "2.128.0",
   "osbapi_version": "2.14",
   "routing_endpoint": "https://api.run.pivotal.io/routing"
}
cf version 6.42.0+0cba12168.2019-01-10

What version of the buildpack you are using?
Apt Buildpack version 0.1.5

If you were attempting to accomplish a task, what was it you were attempting to do?

get mysql-shell installed

What did you expect to happen?
mysql-shell package installs without failures

What was the actual behavior?
Staging app and tracing logs...
   Cell 0a17e4d2-86af-4269-bf35-434c403ddb61 creating container for instance 46ae3507-c619-4ed9-b128-d461fdb76d5f
   Cell 0a17e4d2-86af-4269-bf35-434c403ddb61 successfully created container for instance 46ae3507-c619-4ed9-b128-d461fdb76d5f
   Downloading app package...
   Downloaded app package (7.5M)
   -----> Download go 1.11.4
   -----> Running go build supply
   /tmp/buildpackdownloads/1986c11e5045899f72e33ebceb13b732 ~
   ~
   -----> Apt Buildpack version 0.1.5
   -----> Adding apt keys
 ....
   gpg: Total number processed: 1
   gpg:               imported: 1  (RSA: 1)
   -----> Adding apt repos
   -----> Updating apt cache
   rm: cannot remove '/var/cache/apt/archives/partial/*.deb': Permission denied
   -----> Downloading apt packages
   W: --force-yes is deprecated, use one of the options starting with --allow instead.
   E: Unable to correct problems, you have held broken packages.
          **ERROR** Error running supply: failed apt-get install Reading package lists...
          Building dependency tree...
          Some packages could not be installed. This may mean that you have
          requested an impossible situation or if you are using the unstable
          distribution that some required packages have not yet been created
          or been moved out of Incoming.
          The following information may help to resolve the situation:
          
          The following packages have unmet dependencies:
           mysql-shell : Depends: libprotobuf8 but it is not installable
          
          
          exit status 100
   Failed to run all supply scripts: exit status 14
   Exit status 225
   Cell 0a17e4d2-86af-4269-bf35-434c403ddb61 stopping instance 46ae3507-c619-4ed9-b128-d461fdb76d5f
   Cell 0a17e4d2-86af-4269-bf35-434c403ddb61 destroying container for instance 46ae3507-c619-4ed9-b128-d461fdb76d5f
Error staging application: Staging error: staging failed
FAILED
error running command: exit status 1

Please confirm where necessary:
* [X] I have included a log output
* [X ] My log includes an error message
* [ ] I have included steps for reproduction

apt.yml
---
keys:
- https://raw.githubusercontent.com/,,,
repos:
- deb http://apt.starkandwayne.com stable main
packages:
- mysql-shell

**Comment by kardolus** [comment]
Hi @norman-abramovitz , thanks for bringing this to our attention.

The reason you cannot install mysql-shell is because `libprotobuf8` is not part of cflinuxfs3. What you can do is apt-get that package first. For example from this mirror: https://packages.ubuntu.com/trusty/amd64/libprotobuf8/download. After that you will be able to `apt-get install mysql-shell`.

Just reproduced the above in a docker container using the `cloudfoundry/cflinuxfs3` image

**Comment by drnic** [comment]
Ahh thanks for spotting the libprotobuf8 issue.

Norm - let's try this alternate apt repo -
https://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/#apt-repo-setup

**Comment by drnic** [comment]
This issue can be closed. I think it was my mistake. The `mysql-shell` parent package was trusty specific; and now we're installing a xenial 16.04 package and life is good.

**Comment by kardolus** [comment]
@drnic awesome! sounds good.
