### ISSUE TITLE
No error, but no package installed

### ISSUE THREAD

**Issue by kevinhaeni** [cloudfoundry/apt-buildpack#19]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

- cf version 6.38.0+7ddf0aadd.2018-08-07

What version of the buildpack you are using?

- latest

If you were attempting to accomplish a task, what was it you were attempting to do?

- Installing the smbclient package

**apt.yml**
```
---
packages:
  - smbclient

```

**manifest.yml**
```
---
applications:
- name: MDS_Service
  memory: 1024M
  instances: 2
  disk_quota: 2048M
  buildpacks:
  - https://github.com/cloudfoundry/apt-buildpack.git
  - https://github.com/cloudfoundry/nodejs-buildpack.git
```

What did you expect to happen?

- When logging in with ssh, smbclient should be available or apt list --installed should list  smbclient

What was the actual behavior?

- There is no error, but no signs of the smbclient

>    2019-03-14T15:44:52.51+0100 [STG/0] OUT Downloading build artifacts cache...
>    2019-03-14T15:44:52.51+0100 [STG/0] OUT Downloading app package...
>    2019-03-14T15:44:52.73+0100 [STG/0] OUT Downloaded app package (837K)
>    2019-03-14T15:44:55.19+0100 [STG/0] OUT Downloaded build artifacts cache (56.3M)
>    2019-03-14T15:45:05.47+0100 [STG/0] OUT -----> Download go 1.11.5
>    2019-03-14T15:45:14.16+0100 [STG/0] OUT -----> Running go build supply
>    2019-03-14T15:45:14.16+0100 [STG/0] OUT /tmp/buildpackdownloads/3f6188191ee386ccd86c13b8a9cd4b0d ~
>    2019-03-14T15:45:18.82+0100 [STG/0] OUT ~
>    2019-03-14T15:45:18.82+0100 [STG/0] OUT -----> Apt Buildpack version 0.1.6
>    2019-03-14T15:45:18.83+0100 [STG/0] OUT -----> Updating apt cache
>    2019-03-14T15:45:19.30+0100 [STG/0] ERR rm: cannot remove '/var/cache/apt/archives/partial/*.deb': Permission denied
>    2019-03-14T15:45:20.83+0100 [STG/0] OUT -----> Downloading apt packages
>    2019-03-14T15:45:22.63+0100 [STG/0] ERR W: --force-yes is deprecated, use one of the options starting with --allow instead.
>    2019-03-14T15:45:22.63+0100 [STG/0] OUT -----> Installing apt packages
>    2019-03-14T15:45:24.01+0100 [STG/0] OUT -----> Running go build supply
>    2019-03-14T15:45:24.01+0100 [STG/0] OUT /tmp/buildpackdownloads/50534934fac3192dbe6dfd44b34ba147 ~
>    2019-03-14T15:45:25.85+0100 [STG/0] OUT ~
>    2019-03-14T15:45:25.85+0100 [STG/0] OUT -----> Nodejs Buildpack version 1.6.45

Please confirm where necessary:
* [*] I have included a log output
* [*] My log includes an error message
* [*] I have included steps for reproduction

**Comment by sent1nel** [comment]
We have the same issue.

**Comment by dfreilich** [comment]
@sent1nel Is your issue with `smbclient` as well, or another package?

**Comment by sent1nel** [comment]
`openjdk8-jre`

**Comment by dfreilich** [comment]
Thanks for the post @kevinhaeni and the clarification @sent1nel. We'll look into it further. In the meanwhile, if we could get a sample app, that would always be of help. 

Thanks!

**Comment by tylerphelan** [comment]
@kevinhaeni the installed packages won't show up with `apt list --installed` as they are installed into the droplet instead of the system. If you ssh onto the app you can see them in `/var/vcap/deps/0/apt`. 

FYI to load the app runtime environment in an app container run `/tmp/lifecycle/shell`, then you can see `/var/vcap/deps/0` is on the `PATH`.

It should be noted that the `apt-buildpack` is considered experimental and can have unexpected behavior.

**Comment by Zanadar** [comment]
Closing. Seems like the issue has been addressed.
