### ISSUE TITLE
fails with no internet access

### ISSUE THREAD

**Issue by lrstanley** [cloudfoundry/apt-buildpack#21]
This is an issue I saw after I had issues in https://github.com/cloudfoundry/apt-buildpack/issues/20.

**What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running cf curl /v2/info && cf version?** cf-cli: v6.43.0 and cf version: 2.3.8-build.6.

**What version of the buildpack you are using?** v0.1.7

**If you were attempting to accomplish a task, what was it you were attempting to do?** use an Artifactory based Ubuntu repository, as we are unable to access ubuntu repos directly due to corporate firewall reasons.

**What did you expect to happen?** It to fetch packages from Artifactory as if it were fetching from Ubuntu directly.

**What was the actual behavior?** It fails to validate the ubuntu bionic repository key (because it hits our corporate firewall), and doesn't do anything with the referenced Artifactory repository.

```
Creating app python-example...
Mapping routes...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...
 13.10 KiB / 13.10 KiB  100.00% 1s

Waiting for API to complete processing files...

Staging app and tracing logs...
   Downloading python_buildpack...
   Downloading apt_buildpack...
   Downloaded apt_buildpack (2.2M)
   Downloaded python_buildpack (561.2M)
   Cell ab560f62-dda9-49af-9dfa-1b6c2f16d52f creating container for instance 41ce6f44-71dd-4cf2-b8d4-7c094a4c5ae0
   Cell ab560f62-dda9-49af-9dfa-1b6c2f16d52f successfully created container for instance 41ce6f44-71dd-4cf2-b8d4-7c094a4c5ae0
   Downloading app package...
   Downloaded app package (13.1K)
   -----> Apt Buildpack version 0.1.7
   -----> Adding apt repos
   -----> Updating apt cache
   rm: cannot remove '/var/cache/apt/archives/partial/*.deb': Permission denied
   E: The repository 'http://archive.ubuntu.com/ubuntu bionic InRelease' is not signed.
Error staging application: Staging error: staging failed
FAILED
Deleting app python-example in org myorg / space myspace as myuser...
OK
Renaming app python-example-venerable to python-example in org myorg / space myspace as myuser...
OK
error running command: exit status 1
```
Primarily (it's complaining about it not being signed because it does actually hit a corporate firewall that responds. no key that I would be able to use though):

```
   rm: cannot remove '/var/cache/apt/archives/partial/*.deb': Permission denied
   E: The repository 'http://archive.ubuntu.com/ubuntu bionic InRelease' is not signed.
```

apt.yml

```yaml
---
packages:
- tesseract-ocr
- libtesseract-dev
repos:
- deb https://my-artifactory-hostname/ubuntu-archive-remote bionic universe
```

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

Repro is a little hard, but I think the general solution would have to be a way for me to disable the default repos completely I think. Thoughts?

**Comment by lrstanley** [comment]
Also worth noting I think this would also be useful for those that are direct linking to a .deb file on an http endpoint and don't need ubuntu repositories.

**Comment by ndon55555** [comment]
Hi @lrstanley, thanks for creating this issue. We'll prioritize this soon! Just to confirm, this is using `cflinxufs3` (as per #9 )?

**Comment by lrstanley** [comment]
Yes. To catch you up to speed (been working with Abhi @ pivotal), we tested the priority field (undocumented), with high and low priorities, but for some reason apt still fails when our repos are set with a higher priority. Testing this locally, apt will exit with a zero (ok) statuscode as long as the one with the higher priority succeeds, even if fetching from ubuntu. Testing from the buildpack, it returns a 100 status code.

Also tried giving the ubuntu repositories a negative status code, using the priority field, however, because this buildpack copies the existing /etc/apt/sources.list, it will just add two copies of those ubuntu repositories.

Reviewing the apt properties file, and the supported flags by apt, I don't see an easy way to ignore those types of errors other than the priorities mentioned (but, as shown above, this combination wouldn't work unless apt-buildpack checked to see if the repositories I put in the repo list were already in the sources.list).

I believe at this point, the best option would be to add a yaml option that creates a brand new sources.list, rather than copying the existing one. This would only be a few line changes to support, and is a feature I think others can benefit from.

**Comment by lrstanley** [comment]
Also, when using priorities, it fetches from Artifactory fine. It just fails on ubuntu ones because of the proxy blocking the requests.

**Comment by lrstanley** [comment]
Just FYI, @abhinavrau has a patch that adds truncated sources.list support, as well as cache clean support that resolves our issues. Sounds like a PR will eventually be on it's way.

**Comment by shanks3012** [comment]
@lrstanley We will prioritize this but a PR would definitely be helpful!

**Comment by MaLub** [comment]
We run into same trouble. Doesn't work when we're using a proxy.

**Comment by bcbeatty** [comment]
We upgraded our stack to cflinuxfs3 and we are now getting this issue. It's preventing us from deploying a production release.
Please raise the priority.

**Comment by abhinavrau** [comment]
Hi all,

I have submitted #22 as a fix for this issue. I have written the unit tests but I need some help to write the integration tests. Would love to pair with someone to get this going and merged.

**Comment by dfreilich** [comment]
Hey @abhinavrau, thanks for the fix! It's the top of our backlog, and we'll start work on it on Monday. Our apologies for the delay (@lrstanley, @MaLub , and @bcbeatty), we'll work on finishing the tests and importing the changes ASAP.

**Comment by Zanadar** [comment]
Fixed as of https://github.com/cloudfoundry/apt-buildpack/tree/v0.1.9
