### ISSUE TITLE
Support for HTTPS proxy

### ISSUE THREAD

**Issue by eruvanos** [cloudfoundry/apt-buildpack#23]
## What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

```
{
   "name": "XXXXXXXX",
   "build": "",
   "support": "https://XXXXXXXX",
   "version": 0,
   "description": "",
   "authorization_endpoint": "https://XXXXXXXX",
   "token_endpoint": "https://XXXXXXXX",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "app_ssh_endpoint": "XXXXXXXX:2222",
   "app_ssh_host_key_fingerprint": "c8:f4:e8:b3:0e:44:3f:55:01:cb:67:60:6c:b9:41:47",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://XXXXXXXX:443",
   "api_version": "2.141.0",
   "osbapi_version": "2.15",
   "routing_endpoint": "https://XXXXXXXX",
   "user": "XXXXXXXX"
}
cf version 6.46.1+4934877ec.2019-08-23
```

## What version of the buildpack you are using?
```
0.2.0
```

## If you were attempting to accomplish a task, what was it you were attempting to do?
Install an apt package from behind a proxy, which supports https only.

## What did you expect to happen?
APT buildpack provides a possibility to configure a http and https proxy, furthermore it should be able to install from https repositories.

## What was the actual behavior?
No connection possible.

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

## Related:
There is an issue #20 which seems to refer the same problem, still it is unclear to my, why it was closed.

**Comment by dfreilich** [comment]
Hey @eruvanos , thanks for posting! #20 was closed for an ancillary issue (they were using an old stack), but a solution was provided in #21, with the PR (#22 ) pulled in. Does that thread help at all?

**Comment by eruvanos** [comment]
@dfreilich With the PR (#22 ) we are now able to at least host an apt mirror/cache next to our apps and make it available with internal routes.

But it would be much more reliable to have support for proxy configuration and also for https repositories.

It would really improve the current setup and the use cases in enterprise clouds.

Thanks for your answer.

**Comment by ryanmoran** [comment]
@eruvanos are you unable to use the `http_proxy` environment variable to configure a proxy for `apt` like is described in these docs? https://help.ubuntu.com/community/AptGet/Howto/#Setting_up_apt-get_to_use_a_http-proxy

**Comment by ForestEckhardt** [comment]
We're gonna close this as inactive. Please feel free to re-open if you have further issues.
