### ISSUE TITLE
How to add /opt bin to PATH?

### ISSUE THREAD

**Issue by adborden** [cloudfoundry/apt-buildpack#25]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
API 2.162.0
CLI 7.2.0+be4a5ce2b.2020-12-10

What version of the buildpack you are using?
https://github.com/cloudfoundry/apt-buildpack/commit/3f8d808d0886bd3c15a30fc6b0e2190ae3ec37e5

If you were attempting to accomplish a task, what was it you were attempting to do?
Installing [fluent-bit](https://docs.fluentbit.io/manual/installation/linux/ubuntu) which installs to /opt/td-agent-bit successfully.

```
---
keys:
  - https://packages.fluentbit.io/fluentbit.key
packages:
  - td-agent-bit
repos:
  - deb https://packages.fluentbit.io/ubuntu/bionic bionic main
```

What did you expect to happen?
Would like a configuration option to add /opt/td-agent-bit/bin to PATH as part of the buildpack.

What was the actual behavior?
Binaries are copied to `/home/vcap/deps/0/apt/opt/td-agent-bit/bin/` but not added to path.

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by robdimsdale** [comment]
@adborden did you figure out a workaround for this? Is it still an issue?

**Comment by johnnyr0x** [comment]
Closing because we don't have anymore information on it. If it's still an issue, please re-open/file a new issue.
