### ISSUE TITLE
Q: Will this buildpack continue to work with rootless containers?

### ISSUE THREAD

**Issue by bkrannich** [cloudfoundry/apt-buildpack#6]
Not exactly an issue, but rather a question: With rootless containers becoming the default in Garden at some point in time (https://github.com/cloudfoundry/garden-runc-release#rootless-containers), will this buildpack continue to work?

Thanks,
Bernd

**Comment by sclevine** [comment]
Yep, this buildpack installs apt packages into the droplet as the `vcap` user. It does not require root access.

**Comment by bkrannich** [comment]
@sclevine: Great, thanks!
