### ISSUE TITLE
Server certificate verification failed for https://dist.sapmachine.io/ due to Let's Encrypt DST Root CA X3 expiration

### ISSUE THREAD

**Issue by gregorwolf** [cloudfoundry/apt-buildpack#65]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

- According to the [SAP BTP Release notes](https://help.sap.com/doc/43b304f99a8145809c78f292bfc0bc58/Cloud/en-US/98bf747111574187a7c76f8ced51cfeb.html): 16.23.0
- cf version 7.3.0+645c3ce6a.2021-08-16

What version of the buildpack you are using?

0.2.7

If you were attempting to accomplish a task, what was it you were attempting to do?

In my project [pg-beershop](https://github.com/gregorwolf/pg-beershop/) I'm using the apt-buildpack to create an app that contains the [SapMachine](https://sap.github.io/SapMachine/) JDK and also the NodeJS runtime.  This is defined in [mta.yaml#L24](https://github.com/gregorwolf/pg-beershop/blob/main/mta.yaml#L24). To load the additional package I've defined this [apt.yml](https://github.com/gregorwolf/pg-beershop/blob/main/db-deployer-apt/apt.yml) with the following content:

```YAML
---
keys:
  - https://dist.sapmachine.io/debian/sapmachine.old.key
  - https://dist.sapmachine.io/debian/sapmachine.key
repos:
  - deb http://dist.sapmachine.io/debian/amd64/ ./
packages:
  - sapmachine-11-jdk
```

What did you expect to happen?

The build worked until 30th of September 2021.

What was the actual behavior?

Right now I get the following errors during build:

```
   2021-10-08T07:25:26.82+0200 [STG/0] OUT -----> Apt Buildpack version 0.2.7
   2021-10-08T07:25:26.82+0200 [STG/0] OUT -----> Adding apt keys
   2021-10-08T07:25:26.88+0200 [STG/0] ERR Warning: apt-key output should not be parsed (stdout is not a terminal)
   2021-10-08T07:25:27.29+0200 [STG/0] ERR gpg: no valid OpenPGP data found.
   2021-10-08T07:25:27.29+0200 [STG/0] ERR gpg: Total number processed: 0
   2021-10-08T07:25:27.29+0200 [STG/0] ERR gpg: keyserver communications error: keyserver helper internal error
   2021-10-08T07:25:27.29+0200 [STG/0] ERR gpg: keyserver internal error
   2021-10-08T07:25:27.29+0200 [STG/0] ERR gpg: WARNING: unable to fetch URI https://dist.sapmachine.io/debian/sapmachine.old.key: keyserver error
   2021-10-08T07:25:27.29+0200 [STG/0] OUT        **ERROR** Error running supply: could not add apt key https://dist.sapmachine.io/debian/sapmachine.old.key
   2021-10-08T07:25:27.29+0200 [STG/0] OUT        
   2021-10-08T07:25:27.29+0200 [STG/0] OUT        Executing: /tmp/apt-key-gpghome.D525i3huSB/gpg.1.sh --fetch-keys https://dist.sapmachine.io/debian/sapmachine.old.key
   2021-10-08T07:25:27.29+0200 [STG/0] OUT        gpgkeys: https fetch error 60: server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
```

I think the issue is caused by the fact that the certificate of https://dist.sapmachine.io/ is signed by Let's Encrypt:

![Screenshot 2021-10-08 at 07 40 42](https://user-images.githubusercontent.com/2639535/136504165-6c18b810-d9e8-422b-8e4f-06a1d13d6295.png)

They expired [the DST Root CA X3](https://letsencrypt.org/2021/10/01/cert-chaining-help.html). I think the list of CA Certificates in the file /etc/ssl/certs/ca-certificates.crt needs to be updated.

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction: Please ask me if you need help with the build and deploy

**Comment by mstiunicon** [comment]
same issue for me, can we have a workaround way? like disable the ssl cert?
```
   -----> Apt Buildpack version 0.2.7
          **WARNING** buildpack version changed from 0.2.6 to 0.2.7
   -----> Adding apt keys
   Warning: apt-key output should not be parsed (stdout is not a terminal)
   gpg: no valid OpenPGP data found.
   gpg: Total number processed: 0
   gpg: keyserver communications error: keyserver helper internal error
   gpg: keyserver internal error
   gpg: WARNING: unable to fetch URI https://keyserver.ubuntu.com/pks/lookup?op=get&amp;search=0xEB9B1D8886F44E2A: keyserver error
          **ERROR** Error running supply: could not add apt key https://keyserver.ubuntu.com/pks/lookup?op=get&amp;search=0xEB9B1D8886F44E2A
          
          Executing: /tmp/apt-key-gpghome.12SwVlVXe5/gpg.1.sh --fetch-keys https://keyserver.ubuntu.com/pks/lookup?op=get&amp;search=0xEB9B1D8886F44E2A
          gpgkeys: https fetch error 60: server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
          
          
          exit status 2
          **ERROR** Unable to run all buildpacks: Failed to run all supply scripts: exit status 14
```

**Comment by gregorwolf** [comment]
Correct.

**Comment by sophiewigmore** [comment]
It seems like you need a way to update the certs during staging for the buildpack to access possibly. This seems beyond the apt-buildpack scope. Have you tried following something like https://docs.cloudfoundry.org/running/trusted-system-certificates.html to add the Let's Encrypt Root cert?

**Comment by gregorwolf** [comment]
Seems that the issue was solved by SAP now.
