### ISSUE TITLE
Install specific version of apt instead of latest

### ISSUE THREAD

**Issue by vnpham** [cloudfoundry/apt-buildpack#70]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
{
   "name": "VMware Tanzu Application Service",
   "build": "2.11.6-build.3",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "...",
   "authorization_endpoint": "...",
   "token_endpoint": "...",
   "min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "app_ssh_endpoint": "...",
   "app_ssh_host_key_fingerprint": "...",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "...",
   "api_version": "2.164.0",
   "osbapi_version": "2.15",
   "routing_endpoint": "...",
   "user": "..."
}

cf version 7.3.0+645c3ce6a.2021-08-16

What version of the buildpack you are using?
latest version from github

If you were attempting to accomplish a task, what was it you were attempting to do?
Install a specific version of a package (microsoft sql server odbc driver)

What did you expect to happen?
I would like to know how to specify the exact version of the package I install.  I do not know how to specify that in the apt.yml file.  As a result, a different binary is installed every time there is an update

What was the actual behavior?
The latest version is installed rather than the specific version I want

Please confirm where necessary:
* [] I have included a log output
* [] My log includes an error message
* [] I have included steps for reproduction

**Comment by vnpham** [comment]
Thank you @sophiewigmore, I'm able to confirm that it works with specific version.  I would like to ask a related follow up question as well.  In the example above, what if I want to install the latest major version (3.x.x-x), or the latest major + minor version (3.18.x-x)?  I work with Python and certain tools like pipenv has syntax allowing these mechanism.  Do we have the same thing in apt-buildpack?

Thanks

**Comment by sophiewigmore** [comment]
@vnpham The buildpack essentially runs pre-existent `apt-get install` commands. If there is no native way to do this with `apt` already, then the buildpack isn't capable. From a quick investigation, it doesn't appear that there is a way to do this. There isn't any additional logic in the buildpack to determine the latest version given a major version.

**Comment by vnpham** [comment]
Thank you @sophiewigmore .  I greatly appreciate your help.
